apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: git-clone-alpha
spec:
  inputs:
    # params:
    resources:
      - name: source
        type: git
  steps:
    - name: git-clone
      image: quay.io/srereddy/sample:git-init-v0.12.1
      script: |
        git clone -b $REVISION $GIT_URL
        cd ci-cd-istio-tekton
        RESULT_SHA="$(git rev-parse HEAD | tr -d '\n')"
        echo -n "$RESULT_SHA"
      env:
        - name: GIT_URL
          value: "$(inputs.resources.source.url)"
        - name: REVISION
          value: "$(inputs.resources.source.revision)"
